name: "supercake-test"
services:
  postgres_dev:
    image: postgres:15.13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supercake_dev
    ports:
      - "5434:5432"

  postgres_test:
    image: postgres:15.13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supercake_test
    ports:
      - "5433:5432"
